baseURL = "https://ruriandfox.com"
languageCode = "ja-jp"
title = "Ruri and Fox"
theme = "PaperMod"

[params]
  description = "家族の知恵で楽しく生きる未来を創る"
  author = "Ruri and Fox"
  mainSections = ["services", "contact"]
  defaultTheme = "light"
  disableThemeToggle = true

[menu]
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/#services"
    weight = 1
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/#contact"
    weight = 2
  [[menu.main]]
    identifier = "terms"
    name = "Terms & Policy"
    url = "#"
    weight = 3 